name: "Build project"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout kpeg
        uses: actions/checkout@v2
        with:
          path: kpeg
      - name: "Set up JDK 11"
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
        working-directory: ./kpeg
      - name: "Build project with Gradle"
        run: ./gradlew build --info
        working-directory: ./kpeg
      - name: "Build project docs with Gradle"
        run: ./gradlew mkdocsBuild --info
        working-directory: ./kpeg
      - name: "Upload test reports as an action artifact"
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-test-reports
          path: ./kpeg/lib/build/jacocoHtml
