name: "Publish library docs"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - .github/**
      - .gitattributes
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build-docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew

      - name: "Publish library docs to the Github Pages"
        run: ./gradlew mkdocsPublish
        env:
          GRGIT_USER: ${{ secrets.GRGIT_USER }}
