name: "Publish library snapshot"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - .github/**
      - .gitattributes
      - .gitignore
      - LICENSE
      - README.md

jobs:
  publish-snapshot:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Publish library snapshot to the Maven Central Repository"
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --info
        env:
          PUBLISH_SNAPSHOT: ""
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
